### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by Priyansh2** [bung87/whatlangid#2]
After installing all requirements using pip it fails throwing this error:- `DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
whatlangid requires Python '>=3' but the running Python is 2.7.12`. But it is installed successfully with pip3 instead of pip as error says itself. The document needs an update on usage.

**Comment by bung87** [comment]
**DEPRECATION** is warning level message, **pip3** is an alias for pip in python3 environment
