### ISSUE TITLE
PIP install fails because specified FastText version in `setup.py` is incorrect

### ISSUE THREAD

**Issue by ajaymaity** [bung87/whatlangid#5]
When I simply run:
```
pip install git+https://github.com/bung87/whatlangid
```

I get the following error:
```
Collecting git+https://github.com/bung87/whatlangid
  Cloning https://github.com/bung87/whatlangid to /private/var/folders/6s/rp8k49113cx7bmnff6vdqbshv72s28/T/pip-req-build-flc3_pvu
Collecting fasttext>=0.8.22 (from whatlangid==1.0.9)
  Could not find a version that satisfies the requirement fasttext>=0.8.22 (from whatlangid==1.0.9) (from versions: 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.5.12, 0.5.13, 0.5.14, 0.5.15, 0.5.16, 0.5.17, 0.5.18, 0.5.19, 0.6.0, 0.6.1, 0.6.2, 0.6.4, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3)
No matching distribution found for fasttext>=0.8.22 (from whatlangid==1.0.9)
```

On investigation, I found it is mentioned `fasttext>=0.8.22` in `setup.py`, but PIP doesn't have any such version uploaded in their PyPI repository (https://pypi.org/project/fasttext/#history).  Either the line in `setup.py` should change to FastText Git repository (https://github.com/facebookresearch/fastText) or change the version in `setup.py` to one that is uploaded in PIP.

The latest version in PIP is 0.8.3, but your code references the version 0.8.22, which is why the error.

**Comment by g3rfx** [comment]
I had the same issue. 
You should install fastText from the git repository directly as described here:
https://github.com/facebookresearch/fastText/tree/master/python
Then the installation of whatlangid works.

**Comment by bung87** [comment]
facebook fasttext remove github tag 0.8.22 that's the reason.
as https://github.com/facebookresearch/fastText/releases/tag/v0.9.1 facebook release it to pypi,
 no needs install it from github , since whatlangid v1.0.10 I change the dependency to fasttext>=0.9.1 , thanks you guys!
